### ISSUE TITLE
UnboundLocalError: local variable 'base_urls' referenced before assignment

### ISSUE THREAD

**Issue by zagro-dev** [vict0rsch/ntfy-wrapper#13]
After a new install of 0.1.7 I encountered the following error:

```
[2024-02-22 09:27:32,595] root - ERROR - local variable 'base_urls' referenced before assignment
[2024-02-22 09:27:32,595] root - ERROR - Traceback (most recent call last):
  File "/home/pi/RPi_Relay_Board/python-bottle/utils.py", line 93, in send_ntfy
    ntfy(
  File "/home/pi/.local/lib/python3.9/site-packages/ntfy_wrapper/notifier.py", line 137, in __call__
    return self.notify(*args, **kwds)
  File "/home/pi/.local/lib/python3.9/site-packages/ntfy_wrapper/notifier.py", line 429, in notify
    if not isinstance(base_urls, list) or not base_urls or not base_urls[0]:
UnboundLocalError: local variable 'base_urls' referenced before assignment
```

https://github.com/vict0rsch/ntfy-wrapper/blob/131a5c53ca397ebba5e4be03dc82f576a75643bf/ntfy_wrapper/notifier.py#L429

It doesn't matter if I use the default config or a custom config. I even tried setting multiple urls to test if this works but without success.
Her's my sample conf which gets loaded (I tested with `py-ntfy send --conf-path ...`)

```
[notifier_init]
topics = my-secret-topic
emails = example@example.com
base_url = https://mylocal.domain,http://192.168.1.66:8085

[notify_defaults]
title = My NTFY Title
priority = 0
tags = fire
click = 
attach =
actions =
icon = https://static-00.iconduck.com/assets.00/raspberry-pi-icon-2048x2048-p0y4r07x.png
```

Edit: I tested on a Raspberry Pi with Python 3.9.2

**Comment by zagro-dev** [comment]
Nevermind, after adding `debug_True` to the `ntfy()` function reveiled the true root of the issue:

`requests.exceptions.InvalidHeader: Header part (2) from ('priority', 2) must be of type str or bytes, not <class 'int'>`

After changing the priority from an `int` to a  `str` the error was gone.
